# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assigned_number',
            field=models.IntegerField(default=0),
        ),
    ]
