# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170718_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
    ]
