# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-21 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_candidate_hit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_image2',
            field=models.CharField(default=b'', max_length=1000),
        ),
    ]
