# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170708_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_image',
            field=models.ImageField(upload_to='static/polls/images/'),
        ),
    ]
