# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0016_auto_20161116_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='text',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='title',
        ),
    ]
