# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-26 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0027_auto_20161126_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='createdAt',
            field=models.BigIntegerField(default=1480179875.488),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descendingTime',
            field=models.BigIntegerField(default=-1480179875.487),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updatedAt',
            field=models.BigIntegerField(default=1480179875.488),
        ),
    ]
