# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-27 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0035_auto_20161127_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='createdAt',
            field=models.FloatField(default=1480224927.915),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descendingTime',
            field=models.FloatField(default=-1480224927.915),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=tinymce.models.HTMLField(default=b' '),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descriptionPlainText',
            field=models.TextField(blank=True, default=b' ', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updatedAt',
            field=models.FloatField(default=1480224927.915),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='createdAt',
            field=models.FloatField(default=1480224927.916),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='descendingTime',
            field=models.FloatField(default=-1480224927.916),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='updatedAt',
            field=models.FloatField(default=1480224927.916),
        ),
    ]
