# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0038_auto_20161130_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='position',
            field=geoposition.fields.GeopositionField(default=b'', max_length=42),
        ),
        migrations.AlterField(
            model_name='ad',
            name='createdAt',
            field=models.FloatField(default=1480556951.125),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descendingTime',
            field=models.FloatField(default=-1480556951.125),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updatedAt',
            field=models.FloatField(default=1480556951.125),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='createdAt',
            field=models.FloatField(default=1480556951.127),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='descendingTime',
            field=models.FloatField(default=-1480556951.127),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='updatedAt',
            field=models.FloatField(default=1480556951.127),
        ),
    ]
