# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0003_auto_20161114_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='favoriteCount',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ad',
            name='updatedAt',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
