# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0019_auto_20161116_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='advertiseCount',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='category',
            name='createdAt',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='deepLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='legacy_id',
            field=models.TextField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='nameChinese',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='parentId',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='popular',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='updatedAt',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='createdAt',
            field=models.CharField(default=b'0', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descendingTime',
            field=models.CharField(default=b' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(default=b' '),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descriptionPlainText',
            field=models.TextField(default=b' '),
        ),
        migrations.AlterField(
            model_name='ad',
            name='favoriteCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='flagCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updatedAt',
            field=models.CharField(default=b'0', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='userId',
            field=models.CharField(default=b'Sosokan', max_length=255),
        ),
    ]
