# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0020_auto_20161119_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
