# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0021_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sort_order',
        ),
    ]
