# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0022_remove_category_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updatedAt',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
    ]
