# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0025_auto_20161119_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='createdAt',
            field=models.CharField(default=1479773927.992, max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descendingTime',
            field=models.CharField(default=b'-1479773927.99', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, default=b' ', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='saleOff',
            field=models.TextField(default=b'0', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updatedAt',
            field=models.CharField(default=1479773927.992, max_length=255),
        ),
    ]
