# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-26 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0026_auto_20161121_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='chinese',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='createdAt',
            field=models.BigIntegerField(default=1480179584.543, max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descendingTime',
            field=models.CharField(default=b'-1480179584.54', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='enableEmail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='enablePhone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='feature',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='isChinese',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='isFeatured',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='isHtmlDes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='isStandout',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='legacy_id',
            field=models.TextField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='standout',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updatedAt',
            field=models.BigIntegerField(default=1480179584.543, max_length=255),
        ),
    ]
