# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-26 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0030_auto_20161126_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='adimage',
            name='createdAt',
            field=models.FloatField(default=1480201955.854),
        ),
        migrations.AddField(
            model_name='adimage',
            name='descendingTime',
            field=models.FloatField(default=-1480201955.854),
        ),
        migrations.AddField(
            model_name='adimage',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adimage',
            name='imageUrl',
            field=models.URLField(blank=True, default=b'', null=True),
        ),
        migrations.AddField(
            model_name='adimage',
            name='isStoredInStorage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adimage',
            name='isVideoThumb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adimage',
            name='legacy_id',
            field=models.TextField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adimage',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adimage',
            name='updatedAt',
            field=models.FloatField(default=1480201955.854),
        ),
        migrations.AddField(
            model_name='adimage',
            name='userId',
            field=models.CharField(default=b'Sosokan', max_length=255),
        ),
        migrations.AddField(
            model_name='adimage',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='createdAt',
            field=models.FloatField(default=1480201955.853),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descendingTime',
            field=models.FloatField(default=-1480201955.853),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updatedAt',
            field=models.FloatField(default=1480201955.853),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'files/'),
        ),
    ]
