# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-27 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0033_auto_20161126_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='createdAt',
            field=models.FloatField(default=1480220469.783),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descendingTime',
            field=models.FloatField(default=-1480220469.783),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updatedAt',
            field=models.FloatField(default=1480220469.783),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='createdAt',
            field=models.FloatField(default=1480220469.798),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='descendingTime',
            field=models.FloatField(default=-1480220469.798),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height', null=True, upload_to=b'files/', width_field=b'width'),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='updatedAt',
            field=models.FloatField(default=1480220469.798),
        ),
    ]
