# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-27 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0034_auto_20161126_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='createdAt',
            field=models.FloatField(default=1480223752.956),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descendingTime',
            field=models.FloatField(default=-1480223752.955),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updatedAt',
            field=models.FloatField(default=1480223752.956),
        ),
        migrations.AlterField(
            model_name='ad',
            name='userId',
            field=models.CharField(default=b'HZETmXH25SXNDWVc4ZtNaR07Ru13', max_length=255),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='createdAt',
            field=models.FloatField(default=1480223752.957),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='descendingTime',
            field=models.FloatField(default=-1480223752.957),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='updatedAt',
            field=models.FloatField(default=1480223752.957),
        ),
    ]
