# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-12 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import sosokan.models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0049_auto_20161203_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='createdAt',
            field=models.FloatField(default=1481572462.659),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 12, 14, 54, 22, 659000)),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descendingTime',
            field=models.FloatField(default=-1481572462.659),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updatedAt',
            field=models.FloatField(default=1481572462.659),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='createdAt',
            field=models.FloatField(default=1481572462.661),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='descendingTime',
            field=models.FloatField(default=-1481572462.661),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(default='', height_field=b'height', upload_to=b'images/', validators=[sosokan.models.validate_image], width_field=b'width'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adimage',
            name='updatedAt',
            field=models.FloatField(default=1481572462.661),
        ),
    ]
