# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-27 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import sosokan.models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0097_auto_20170313_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='background',
            field=models.ImageField(default=None, null=True, upload_to=b'images/', validators=[sosokan.models.validate_image]),
        ),
    ]
