# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170707_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_image',
            field=models.ImageField(default='static/polls/images/Desertsmall.jpg', upload_to=''),
        ),
    ]
