# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_candidate_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_image',
            field=models.ImageField(default='Desertsmall.jpg', upload_to=''),
        ),
    ]
