# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0004_auto_20161116_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='active',
        ),
    ]
