# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0011_auto_20161116_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='feature',
            field=models.NullBooleanField(default=None),
        ),
    ]
