# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0012_auto_20161116_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='isChinese',
            field=models.NullBooleanField(default=None),
        ),
    ]
