# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosokan', '0023_auto_20161119_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nameChinese',
            field=models.CharField(blank=True, default=b'', max_length=200, null=True),
        ),
    ]
